version: 2026.3.25

logging:
  level: INFO
  format: text
  file:
    enabled: true
    path: ./logs/haze-weather-radio.log
    rotate:
      enabled: true
      max_bytes: 10485760
      backup_count: 5
  console:
    enabled: true

playout:
  sample_rate: 16000
  channels: 1

  playlist_order:
    - alerts:
      ttl: 120
    - station_id
    - date_time:
      ttl: 10
    - current_conditions:
      ttl: 2700
    - forecast:
      ttl: 7200
    - date_time:
      ttl: 10
    - climate_summary:
      ttl: 28800
    - eccc_discussion:
      ttl: 10800
    - geophysical_alert:
      ttl: 10800
    - user_bulletin:
      ttl: 3600

operator:
  on_air_name: "Betteradio Canada"
  operator_name: "meow raii"
  email: "meow rye @mist w x .com"
  phone: "6 3 9 - 8 7 2 - 9 0 8 8 "

wx_on_demand: # haze can accept a POST request from external applications with a location code, request packages, and other parameters to generate on demand packages for that location which is then returned to the requester. if the location code matches one of the feed's locations, it will re-use the data and TTS audio files that it has already generated for that location to create the requested package.

  # my plans for this is to have asterisk call a webhook on this app when someone calls a phone number for weather information, and the caller can input their location code using the phone keypad to get a forecast package for their location read back to them over the phone using the TTS engine and audio files generated by haze. this way, you can have an automated telephone weather service without needing to pay for a third party service (ugh).
  enabled: true
  cors: [
    allow_origins: ["127.0.0.1"],
    allow_methods: ["POST"],
    allow_headers: ["*"]
  ]
  endpoint-base: /api/v1/wx-on-demand/
  # example: http://127.0.0.1:8080/api/v1/wx-on-demand/sk-40?package_types=current,forecast&voice=male&lang=en-CA&source=eccc&format=opus
  # example: http://127.0.0.1:8080/api/v1/wx-on-demand/geo,code?package_types=current,forecast&voice=male&lang=en-CA&source=twc&format=ulaw
  # example: http://127.0.0.1:8080/api/v1/wx-on-demand/CPUN?package_types=current,forecast&voice=male&lang=en-CA&source=twc&format=g722

webpanel:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  cors: [
    allow_origins: ["127.0.0.1"],
    allow_methods: ["POST"],
    allow_headers: ["*"]
  ]
  rest_api: [
    enabled: true,
    base_path: /api/v1/
  ]
  authentication:
    enabled: true # if disabled, the panel will be read-only and the REST API will only accept requests from 127.0.0.1 without authentication. this is because you probably don't want to grant everyone on the intranet the ability to air their own weather alerts. that would be bad.
    password: HackMeMommy!12# # change this lol. it needs to be at least 8 characters long, contain at least: three uppercase letters, four lowercase letters, two numbers, and two special characters.
    # blank to autogenerate a random one time password on startup and print it in the logs.

twc_api_key: "e1f10a1e78da46f5b10a1e78da96f525"
twc_units: m
language: en-CA

feeds:
  - id: sk-saskatoon
    callsign: VDI651
    enabled: true
    timezone: America/Regina
    data_source: eccc # api.weather.gc.ca (ECCC), api.weather.gov (NWS), or api.weather.com (TWC).

    languages: # a list of languages that the feed can broadcast in. it is ordered by preference, with the first language being the first to broadcast, then switching to the next language in the list after a predefined interval or when there are no more items to broadcast in the current language. this allows for multilingual broadcasts without needing separate feeds for each language.
      en-CA:
        interval: 0 # number of consecutive times to broadcast in this language before switching to the next language in the list. if it is 0, 1, or undefined, it will broadcast all items in this language once before switching to the next language.
      fr-CA:
        interval: 0

    description: # for station identification.
      en-CA:
        text: "This is an automated broadcast, servicing the city of Saskatoon with the latest weather alerts and forecasts originating from Environment Canada."
        suffix: "This service is not affiliated with Environment Canada."

      fr-CA:
        text: "Ceci est une diffusion automatisée desservant la ville de Saskatoon avec les dernières alertes météorologiques et prévisions provenant d'Environnement Canada."
        suffix: "Ce service n'est pas affilié à Environnement Canada."
    
    locations: # first one is the primary service location, used for SAME headers and other location-based features. additional locations can be added for broader coverage. required test and service-wide alerts will include all SAME location codes from all locations in the feed.

    # ID: Either an Environment Canada City Page ID, a National Weather Service County/Zone code, or an IATA (METAR) station ID for both NWS and TWC.

    # FORECAST_REGION: Either a Canadian Location Code (CLC) for ECCC paired with a City Page code. Or a NWS zone code paired with a county code. forecast_region is required for alert matching, but ECCC/NWS data depend on the id.

    # SOURCE: Use ECCC's City Page product, or use the National Weather Service API. if using ECCC, the id must be an Environment Canada City Page ID. if using NWS or TWC, the id must be an IATA (METAR) station ID.

    # NAME_OVERRIDE: sometimes, a given source wont provide a location name within the API response. such as the NWS API (because it is designed for American locations and not Canadian ones), or the weather.com/TWC API (because location names are provided in a different endpoint that this app does not currently integrate with). in these cases, you can provide a name override here to specify the location name to use for this location for this feed. if not provided, it will default to the station ID. which is not ideal. like DirecTV Local On The 8s type ideal.

      - observationLocations:
        - id: sk-40 # Saskatoon
          source: eccc
        - id: sk-1 # Rosthern
          source: eccc
        - id: sk-6 # Humboldt
          source: eccc
        - id: CWIW # Watrous
          source: nws
          name_override: "Watrous"
        - id: sk-37 # Outlook
          source: eccc
        - id: CWRJ # Rosetown
          source: twc
        - id: sk-2 # Biggar
          name_override: "Biggar"
          source: eccc
        - id: sk-34 # North Battleford
          source: eccc
        - id: sk-18 # Elbow
          source: eccc
        
      - forecastLocations:
        - id: sk-40 # Saskatoon
          forecast_region: "065100"
          source: eccc
        - id: sk-1
          forecast_region: "065400-06543*" # can use wild card to match multiple subregions within the same region. in this case, it would include the R.M.s of 065431 to 065436.
          source: eccc
        - id: sk-49
          forecast_region: "065500-065521" # can include a subregion code to target a specific region only for weather alerts.
          source: eccc
          
      - climateLocations:
        # ID: Environment Canada virtual climate station id for LTCE daily records.
        # CITYPAGE_ID: optional explicit WXO/citypage id used to pull regional normals. if omitted, haze derives it from the climate id when they share the same base code, for example VSSK40V -> sk-40.
        - id: VSSK40V
          source: eccc
          # citypage_id: sk-40

    output: # multiple outputs can be configured, none for only audio file generation without playout, streaming, or broadcasting. if multiple outputs are enabled, the same audio will be sent to all of them simultaneously.
      stream:
        enabled: true
        type: icecast
        mount: # blank will use /{feed_id}
        host: icecast.almora.tv
        port: 8443
        username: source
        password: aluser
        ssl: false
        format: opus
        bitrate_kbps: 32

      audio_device:
        enabled: false
        device_name: null # if null, the default audio output device will be used. otherwise, specify the name of the audio output device to use for playback. this can be found using tools like `aplay -l` on linux or `ffmpeg -hide_banner -list_devices true -f dshow -i dummy` on windows.

      PiFmAdv: # it is unknown if this is actually working as it bottlenecks my raspberry pi model 3b+. maybe someone with a powerful enough raspberry pi can help optimize this and make a pull request?
        bin_root: /home/rai/PiFmAdv/src # root directory of the PiFmAdv binary on your local machine or the remote machine if using ssh.
        enabled: true # enable this output?
        frequency_mhz: 162.450 # frequency to broadcast on in hertz.
        tx_power: 0 # transmission power level from 0 to 7. 0 is the lowest power and 7 is the highest. the actual range will depend on your hardware and antenna setup.
        alternative_frequencies: [] # PiAdvFm accepts this parameter but i dont know how to use it. so ill just pass whatever you put here to the binary.
        bandwidth_hz: 10000 # bandwidth of the actual transmitted signal
        deviation_hz: 5000 # frequency deviation for fm modulation. weather radio is typically 5000 hz.
        ssh: # i have this wonderful idea where i can have the audio generated on a more powerful machine and then use ssh to run the PiFmAdv binary on the raspberry pi
        #      and stream raw pcm to it 
          enabled: true # if false, the PiFmAdv binary will be run locally on the same machine as this app. if true, the binary will be run on a remote machine over ssh.
          ffmpeg_bin: ffmpeg # path to ffmpeg binary on this machine (local). if it is in the PATH, then just the name of the binary is fine.
          ssh_bin: ssh
          host: 172.16.1.37
          port: 22
          username: rai
          password:
          public_key_path: ~/.ssh/almora


cap:
  cap_cp:
    enabled: true
    name: Alert Ready (CAP-CP)
    sources:
      - id: naads
        streaming1url: streaming1.naad-adna.pelmorex.com:8080/
        streaming2url: streaming2.naad-adna.pelmorex.com:8080/
        capcp1: https://capcp1.naad-adna.pelmorex.com/
        capcp2: https://capcp2.naad-adna.pelmorex.com/
        poll_interval_seconds: 60
        timeout_seconds: 10
    filter:
      use_feed_locations: true # whether to filter alerts based on the locations defined in the feed. if true, only alerts that match the SAME location codes of the feed's locations will be included. if false, all alerts are subject to the settings below.
      geocodes: ["4711*", "4712*"] # can wild card with * to match any geocode that starts with the specified string.
      blocklist: [ # leave any array empty to not filter by that parameter.
        severity: ["Minor", "Unknown"], # block alerts with these severities. valid values are Extreme, Severe, Moderate, Minor, and Unknown.
        certainty: ["Unknown", "Past"], # block alerts with these certainties. valid values are Immediate, Expected, Future, Past, and Unknown.
        urgency: [],
        status: [],
        scope: [],
      ]
    dedup:
      window_seconds: 300
      key_fields:
        - identifier
        - sent
  nws_cap:
    enabled: false
    name: National Weather Service (NWS CAP)
    sources:
      - id: nws_api
        url: https://api.weather.gov/alerts/active.atom
        use_feed_locations: false # whether to filter alerts based on the locations defined in the feed. if true, only alerts that match the SAME location codes of the feed's locations will be included. if false, all alerts with any county code will be toned.
        querys: [
          "status=actual",
          "message_type=alert,update",
          "severity=extreme,severe,moderate",
          "urgency=immediate,expected",
          "certainty=observed,likely,possible",
        ]

same:
  sender: "MEWRAI:3" # SAME header sender field (callsign or other identifier, max 8 chars. will be either truncated or padded with spaces to 8 chars in the actual SAME message).

  weeklytest: # parameters for Required Weekly Test or Required Monthly Test SAME messages
  #               Typically on Weatheradio Canada, the RWT is broadcast every Wednesday at noon local time, and RMT is broadcast on the first Wednesday of each month at noon local time.
    enabled: true
    weeks: [2, 3, 4] # broadcast the weekly test on these weeks of the month on the specified weekday at the specified time.
    weekday: wed
    hour: 12 # in local time of the station.
    minute: 0
    second: 0
    event_code: RWT
    same_expir: 0030 # 30 minutes in SAME.
  
  monthlytest:
    enabled: true
    week: 1 # broadcast the monthly test on this week of the month on the specified weekday at the specified time.
    weekday: wed # wed
    hour: 12
    minute: 0
    second: 0
    event_code: RMT
    same_expir: 0030 # 30 minutes in SAME.
  
  default_attention_tone: WXR # WXR is the 8 second 1050hz tone, NPAS is the Canadian Alerting Attention Signal, which is an 8 second sequence of alternating, 500ms tones. (i hope that kid flipping dies), EAS is an 8 second dual-tone signal of 853 hz and 960 hz sine waves, and egg_timer is the old attention tone used in Ontario's Weatheradio Canada network until 2021 before the AVIPADS system was decommissioned in favor of INOTIFY.

  attention_tone_override: # override the default attention tone for specific event codes. if an event code is not listed here, the default_attention_tone will be used.
    - TOR: WXR
  
  alert_ready_on_NAADS_BIP: true # use the NPAS attention tone for NAADS CAP-CP alerts if they are marked for BI (Broadcast Immediate) on Alert Ready.

  send_txp_on_startup: false # whether to send a Transmitter Primary On SAME message on startup. there is no audio message or attention tone associated with this message.

network:
  use_system_defaults: true
  interfaces:
    - name: default
      enabled: true
      bind_address: 0.0.0.0
      dns:
        - 1.1.1.1
        - 8.8.8.8
  requests:
    connect_timeout_seconds: 5
    read_timeout_seconds: 15
    retries: 3
    backoff_seconds: 1.5

tts:
  default_backend: piper

  lang:
    en-CA:
      backend:
        piper:
          male:
            model: ./piper-tts/en_US-hfc_male-medium.onnx
            speaker: 0 # 0 for default speaker, or the index of the speaker in the model if it contains multiple speakers.
            config: ./piper-tts/en_US-hfc_male-medium.onnx.json
          female:
            model: ./piper-tts/en_US-lessac-high.onnx
            speaker: 0
            config: ./piper-tts/en_US-lessac-high.onnx.json
    fr-CA:
      backend:
        piper:
          male:
            model: ./piper-tts/fr_FR-upmc-medium.onnx
            speaker: 1
            config: ./piper-tts/fr_FR-upmc-medium.onnx.json
          female: None

  pyttsx3:
    enabled: true
    voice: english
    rate: 180
    volume: 1.0

  fallback_order:
    - piper
    - pyttsx3
