version: 2026.3.25

logging:
  level: INFO
  format: text
  file:
    enabled: true
    path: ./logs/haze-weather-radio.log
    rotate:
      enabled: true
      max_bytes: 10485760
      backup_count: 5
  console:
    enabled: true

playout:
  sample_rate: 11025
  channels: 1
  default_playlist: null
  shuffle: true
  shuffle_carry_over: 3
  playlist_order:
    - date_time
    - station_id
    - current_conditions
    - forecast
    - date_time
    - eccc_discussion
    - geophysical_alert
    - user_bulletin

operator:
  on_air_name: "Betteradio Canada"
  owner: "meowraii"
  email: ""
  phone: ""

wx_on_demand: # haze can accept a POST request from external applications with a location code, request packages, and other parameters to generate on demand packages for that location which is then returned to the requester. if the location code matches one of the feed's locations, it will re-use the data and TTS audio files that it has already generated for that location to create the requested package.

  # my plans for this is to have asterisk call a webhook on this app when someone calls a phone number for weather information, and the caller can input their location code using the phone keypad to get a forecast package for their location read back to them over the phone using the TTS engine and audio files generated by haze. this way, you can have an automated telephone weather service without needing to pay for a third party service (ugh).
  enabled: true
  port: 5020 # separate from the webpanel/REST API.
  cors: [
    allow_origins: ["127.0.0.1"],
    allow_methods: ["POST"],
    allow_headers: ["*"]
  ]
  endpoint-base: /wx-on-demand/v1/
  # example: http://127.0.0.1:5020/wx-on-demand/v1/SK-40?package_types=current,forecast&voice=male&lang=en-CA&source=eccc
  # example: http://127.0.0.1:5020/wx-on-demand/v1/geo,code?package_types=current,forecast&voice=male&lang=en-CA&source=twc
  # example: http://127.0.0.1:5020/wx-on-demand/v1/CPUN?package_types=current,forecast&voice=male&lang=en-CA&source=twc

webpanel:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  cors: [
    allow_origins: ["127.0.0.1"],
    allow_methods: ["POST"],
    allow_headers: ["*"]
  ]
  rest_api: [
    enabled: true,
    base_path: /api/v1/
  ]
  authentication:
    enabled: true # if disabled, the panel will be read-only and the REST API will only accept requests from 127.0.0.1 without authentication. this is because you probably don't want to grant everyone on the intranet the ability to air their own weather alerts. that would be bad.
    password: HackMeMommy!12# # change this lol. it needs to be at least 8 characters long, contain at least: three uppercase letters, four lowercase letters, two numbers, and two special characters.
    # blank to autogenerate a random one time password on startup and print it in the logs.

feeds:
  - id: sk-saskatoon
    name: Saskatoon Regional Broadcast
    enabled: true
    timezone: America/Regina
    data_source: eccc # api.weather.gc.ca (ECCC), api.weather.gov (NWS), or api.weather.com (TWC).

    languages: # a list of languages that the feed can broadcast in. it is ordered by preference, with the first language being the first to broadcast, then switching to the next language in the list after a predefined interval or when there are no more items to broadcast in the current language. this allows for multilingual broadcasts without needing separate feeds for each language.
      en-CA:
        interval: 0 # number of consecutive times to broadcast in this language before switching to the next language in the list. if it is 0, 1, or undefined, it will broadcast all items in this language once before switching to the next language.
      fr-CA:
        interval: 0

    description: # for station identification.
      en-CA:
        prefix: ""
        text: "This is an automated broadcast, servicing the city of Saskatoon with the latest weather alerts and forecasts originating from Environment Canada."
        suffix: "This service is not affiliated with Environment Canada."

      fr-CA:
        prefix: ""
        text: "Ceci est une diffusion automatisée desservant la ville de Saskatoon avec les dernières alertes météorologiques et prévisions provenant d'Environnement Canada."
        suffix: "Ce service n'est pas affilié à Environnement Canada."
    
    locations: # first one is the primary service location, used for SAME headers and other location-based features. additional locations can be added for broader coverage. required test and service-wide alerts will include all SAME location codes from all locations in the feed.
      - name: City of Saskatoon
        province_state: SK
        generate_forecast: true # whether to generate a forecast package for this location using the TTS engine. if false, only current conditions and alerts will be broadcast for this location. the forecast package is quite lengthy and covers a broad location around the station, so it would not be desirable to have overlapping forecast packages for multiple locations in the same feed. therefore, only one location per feed can have this enabled. if none have it enabled, then nothing happens lmao. this also applies to the air quality forecast.
        eccc_id: sk-40 # location code if the data source is environment canada.
        geocode: 52.1,-106.67 # geocode if the data source is weather.com (TWC).
        station_id: CYXE # location code if the data source is weather.gov (NWS).
        bye_weather: 06040 # 'Hello Weather' original location code. maybe this app can be used for an automated telephone weather service instead of just Weatheradio. because after Hello Weather shut down, an alternative number for weather popped up. and it was fucking 40 dollars a month. information deserves to be free. also the website looks vibecoded. which is ironic because this app is also kinda vibecoded. but at least this app is open source and can be self hosted for free instead of being a cash grab. oh btw this is optional and can be set to None without breaking stuff.
        same: "065100" # can support multiple regions, and also can take a wildcard.
      - name: Lake Lenore. Humboldt. Pilger.
        province_state: SK
        generate_forecast: false
        eccc_id: sk-6
        geocode: 52.2,105.12
        station_id: CPUN
        bye_weather: None
        same: "" # this location wont be included in SAME alerts.
      - name: Watrous. Young. Zelma.
        province_state: SK
        generate_forecast: false
        eccc_id: sk-49
        geocode: 51.75,-105.85
        station_id: CWIW
        bye_weather: None
        same: "06553*"
      - name: Outlook. Glenside.
        province_state: SK
        generate_forecast: true
        eccc_id: sk-37
        geocode: 51.49,-107.03
        station_id: CWYE
        bye_weather: None
        same: "06552*"

    alerts:
      cap_cp:
        enabled: true
      nws:
        enabled: false

    output: # multiple outputs can be configured, none for only audio file generation without playout, streaming, or broadcasting. if multiple outputs are enabled, the same audio will be sent to all of them simultaneously.
      stream:
        enabled: true
        type: icecast
        mount: # blank will use /{feed_id}
        host: icecast.almora.tv
        port: 8443
        username: source
        password: aluser
        ssl: false
        format: opus
        bitrate_kbps: 32

      audio_device:
        enabled: false
        device_name: null # if null, the default audio output device will be used. otherwise, specify the name of the audio output device to use for playback. this can be found using tools like `aplay -l` on linux or `ffmpeg -hide_banner -list_devices true -f dshow -i dummy` on windows.

      PiFmAdv:
        bin_root: /home/rai/PiFmAdv/src
        enabled: false
        frequency_hz: 162475000 # 162.550 Mhz (XLF322) is currently taken because Environment Canada is burning cash by looping a discontinuation bulletin instead of just shutting down the transmitters.
        sample_rate_hz: 8000 # reencode audio input to this sample rate for transmission
        bandwidth_hz: 12500 # bandwidth of the actual transmitted signal
        modulation: fm
        deviation_hz: 5000 # frequency deviation for fm modulation

cap:
  cap_cp:
    enabled: true
    name: Alert Ready (CAP-CP)
    sources:
      - id: naads
        streaming1url: streaming1.naad-adna.pelmorex.com:8080/
        streaming2url: streaming2.naad-adna.pelmorex.com:8080/
        capcp1: https://capcp1.naad-adna.pelmorex.com/
        capcp2: https://capcp2.naad-adna.pelmorex.com/
        poll_interval_seconds: 60
        timeout_seconds: 10
    filter:
      use_feed_locations: false # whether to filter alerts based on the locations defined in the feed. if true, only alerts that match the SAME location codes of the feed's locations will be included. if false, all alerts are subject to the settings below.
      geocodes: [] # can wild card with * to match any geocode that starts with the specified string.
      blocklist: [ # leave any array empty to not filter by that parameter.
        severity: [], # block alerts with these severities. valid values are Extreme, Severe, Moderate, Minor, and Unknown.
        certainty: [],
        urgency: [],
        status: [],
        scope: [],
      ]
    dedup:
      window_seconds: 300
      key_fields:
        - identifier
        - sent

  nws:
    enabled: false
    name: NWS CAP
    sources:
      - id: nws-active-alerts
        url: https://api.weather.gov/alerts/active.atom
        poll_interval_seconds: 60
        timeout_seconds: 10
    filter:
      geocodes: []
      states:
        - WA
      severities:
        - Extreme
        - Severe

same:
  sender: "BTTRADIO" # SAME header sender field (callsign or other identifier, max 8 chars. will be either truncated or padded with spaces to 8 chars in the actual SAME message).

  weeklytest: # parameters for Required Weekly Test or Required Monthly Test SAME messages
  #               Typically on Weatheradio Canada, the RWT is broadcast every Wednesday at noon local time, and RMT is broadcast on the first Wednesday of each month at noon local time.
    enabled: false
    weeks: [2, 3, 4] # broadcast the weekly test on these weeks of the month on the specified weekday at the specified time.
    weekday: wed
    hour: 12 # in local time of the station.
    minute: 0
    second: 0
    event_code: RWT
    same_expir: 0030 # 30 minutes in SAME.
  
  monthlytest:
    enabled: false
    week: 1 # broadcast the monthly test on this week of the month on the specified weekday at the specified time.
    weekday: wed
    hour: 12
    minute: 0
    second: 0
    event_code: RMT
    same_expir: 0030 # 30 minutes in SAME.
  
  default_attention_tone: WXR # WXR is the 8 second 1050hz tone, NPAS is the Canadian Alerting Attention Signal, which is an 8 second sequence of alternating, 500ms tones. (i hope that kid flipping dies), EAS is an 8 second dual-tone signal of 853 hz and 960 hz sine waves, and egg_timer is the old attention tone used in Ontario's Weatheradio Canada network until 2021 before the AVIPADS system was decommissioned in favor of INOTIFY.

  attention_tone_override: # override the default attention tone for specific event codes. if an event code is not listed here, the default_attention_tone will be used.
    - TOR: WXR
  
  alert_ready_on_NAADS_BIP: true # use the NPAS attention tone for NAADS CAP-CP alerts if they are marked for BI (Broadcast Immediate) on Alert Ready.
      # 1. Broadcast Immediate Parameter

      # The Broadcast Immediate Parameter (BIP) provides an indicator that the content of an alert message is intended for immediate broadcast by LMDs.

          #1.1. A CAP <parameter> shall be used to indicate when the criteria for a BI alert, as defined by the “Broadcast Immediate Events List”, have been met.
          #1.2. This <parameter> will be described as the Broadcast Immediate Parameter or BIP.
          #1.3. A BIP is an optional CAP element and is not required for non-BI alerts.  This includes alerts that don't meet the BI criteria and those do meet the BI criteria (Event, Urgency, Severity, Certainty) but are not intended for broadcast distribution.
          #1.4. For alerts that do meet the BI criteria, a BIP is required in order to properly indicate whether the alert is intended for immediate broadcast.
          #1.5. The <valueName> of the BIP <parameter> is “layer:SOREM:1.0:Broadcast_Immediately”. This <valueName> shall conform to the CAP-CP <valueName> Scheme. (i.e., naming conventions, versioning, case-insensitivity, etc.).
          #1.6. The BIP <parameter> <value> shall be either “yes” to indicate the alert is intended for immediate broadcast or “no” to indicate it is not. The <value> is case-insensitive and shall contain no other characters or whitespace.
          #1.7. A single BIP element is allowed in an <info> element.
          #1.8. When an alert contains multiple <info> elements, each <info> element should have a single respective BIP to indicate whether the <info> element meets the BI criteria. An alert therefore may have <info> elements that are BI and non-BI.
          #1.9. Multiple languages are supported via multiple <info> elements, each with a single respective BIP. Where the content of <info> elements differs only by language, i.e. translated free form text, the BIP <value> of those <info> elements should be the same.
          #1.10. The audience alert message for a BI alert shall be derived from <info> elements that have a BIP <value> of “yes”.

  send_txp_on_startup: true # whether to send a Transmitter Primary On SAME message on startup. there is no audio message or attention tone associated with this message.

network:
  use_system_defaults: true
  interfaces:
    - name: default
      enabled: true
      bind_address: 0.0.0.0
      dns:
        - 1.1.1.1
        - 8.8.8.8
  requests:
    connect_timeout_seconds: 5
    read_timeout_seconds: 15
    retries: 3
    backoff_seconds: 1.5

tts:
  default_backend: piper

  lang:
    en-CA:
      backend:
        piper:
          male:
            model: ./piper-tts/en_US-hfc_male-medium.onnx
            speaker: 0 # 0 for default speaker, or the index of the speaker in the model if it contains multiple speakers. this allows for voice customization without needing separate models for each voice. the available speakers can be found in the model's config json file under the "speakers" field. if the model only contains one speaker, this can be left as 0 or undefined.
            config: ./piper-tts/en_US-hfc_male-medium.onnx.json
          female:
            model: ./piper-tts/en_US-lessac-high.onnx
            speaker: 0
            config: ./piper-tts/en_US-lessac-high.onnx.json
    fr-CA:
      backend:
        piper:
          male:
            model: ./piper-tts/fr_FR-upmc-medium.onnx
            speaker: 1
            config: ./piper-tts/fr_FR-upmc-medium.onnx.json
          female: None

#  pyttsx3:   for future implementation
#    enabled: true
#    voice: english
#    rate: 180
#    volume: 1.0

#  fallback_order:
#    - piper
#    - pyttsx3
